### PR TITLE
Louise

### PR DESCRIPTION
**Pull request by louise-hsu**
Spectrogram functions

- notes: start_time = middle of file, duration: 0.5 sec
- instruments: start_time = 1/6 of the file, duration : 1 sec

renamed the models; not fashion model anymore

### CODE REVIEW

**Review by Calistic — APPROVED** [review]
Added which section of sound file to use in spectrogram

**Review by Calistic — CHANGES_REQUESTED** [review]
Need to remove old commits.

**Review by susiexia — APPROVED** [review]
approve change

**Review by susiexia — APPROVED** [review]
changes approved

**Review by Calistic — APPROVED** [review]

**Review by susiexia — APPROVED** [review]
changes approved

**Pull request merged**
